### ISSUE TITLE
Confused about the page.

### ISSUE THREAD

**Issue by Cyberdroid1** [BenSova/Patched-Sur#117]
![Screenshot 2020-12-05 at 18 09 25](https://user-images.githubusercontent.com/51435948/101243286-1759a280-3725-11eb-87c5-a8917a12919c.png)

Please explain what does this screen mean. Does it mean that I am up-to-date or not supported, or that I can use Software update in System Preferences.
I have successfully installed Big Sur on my Mac.

**Comment by BenSova** [comment]
There's supposed to be the word not there... 

Updating macOS inside the post install app is a coming feature that I am working on. You can update one of three things with it:

- The patcher app itself
- macOS, just like you did before with System Preferences
- The kext patches, so when there are more stable ones it will prompt you to use those.

You can't use System Preferences because you are still on an unsupported Mac and the update compatibility checks still fail, just like they did in Catalina. So, this section will try to provide the most seamless experience when trying to update.

**Comment by Cyberdroid1** [comment]
Oh ok, got it!
