### ISSUE TITLE
"The following disk images couldn't be opened"

### ISSUE THREAD

**Issue by Mennaruuk** [BenSova/Patched-Sur#123]
**Describe the bug**
I can't mount the Patched-Sur.dmg file.

**To Reproduce**
1. [Download v0.0.4](https://github.com/BenSova/Patched-Sur/releases/download/v0.0.4/Patched-Sur.dmg).
2. Double click the .dmg file.
3. Wait for the error.

**Expected behavior**
Disk image should be properly mounted.

**Screenshots**

![4DE8C980-034B-4EC5-B0B5-7F5B634128F8](https://user-images.githubusercontent.com/52135169/101298507-498a0380-37fc-11eb-8503-762687fcb9dd.jpg)

**Desktop (please complete the following information):**
 - Upgrading from: El Capitan
- Upgrading to: Big Sur v11.0 ([checksum](https://zerobin.net/?5afbd9cc9570b6c4#mFZD2QgO8g/m8pmpNM/552XChBD+FptfwpmPpswqxVU=))
 - Mac Model: [2008 iMac](https://everymac.com/systems/apple/imac/specs/imac-core-2-duo-2.4-20-inch-aluminum-early-2008-penryn-specs.html)
 - Version: v0.0.4

**Additional context**
Running El Capitan on 2008 Penryn-based iMac.

**Comment by BenSova** [comment]
This is not a bug. The app only opens on Catalina and up, the dmg only opens on High Sierra and up (it's APFS). In addition to that your 2008 Mac Pro shouldn't even be used with this patcher, not only is there no graphics acceleration, but the lack of pretty much any optimization because there is a better patcher for that Mac will also help you experience boot loops later on. 

**You should be using StarPlayrX's [bigmac](https://github.com/StarPlayrX/bigmac) patcher**
