### ISSUE TITLE
MacBook Pro (Retina, 13-inch, Late 2012) - Cannot install

### ISSUE THREAD

**Issue by lstorino** [BenSova/Patched-Sur#327]
**Describe the bug**
I have followed all the process, decrypted the SSD by turning FileVault off,  the installation flows fine until the boot.
When I boot and select the USB drive I have created I get a forbidden sign and a website

https://support.apple.com/en-us/HT210901

So.... I probably have to wait a bit longer

**Comment by BenSova** [comment]
# Did you happen to along the way boot into the EFI Boot

I'm just going to keep on using that hashtag.

**Comment by ozziepadilla** [comment]
Probably some people booting the mac 💻 but they don’t select the EFI boot , benSova I have seen few videos on YouTube that the guys using your patched Sur but skipping the EFI boot on the explanation, I guess everyone goes by watching YouTube videos because they don’t saying everything your procedures from your page and also I don’t understand why they suggest to run CRSUTIL disable on the terminal

**Comment by lstorino** [comment]
EFI Boot addressed all the question! Now is running smoothly... Thank you so much for reminding me of this step!

**Comment by ozziepadilla** [comment]
What did I said people skipped the EFI boot
