### ISSUE TITLE
FileVault is open... but it is not

### ISSUE THREAD

**Issue by skfar** [BenSova/Patched-Sur#408]
PatchedSur gives me warning that FileVault is open... but it is disabled (I've checked twice). 

How did this happen? I was doing something and left FileVault open... then I started patching. After that I have received warning that FileVault is open. So I have closed it, but warning still appears.

![filevault](https://user-images.githubusercontent.com/80716154/111213202-cfbe9e80-85d0-11eb-8515-4e5e321a0f69.jpg)

**Desktop (please complete the following information):**
 - Upgrading from: Catalina v10.15.7
- Upgrading to: Big Sur v11.1 
 - Mac Model: 13" Mid 2012 MacBook Pro
 - Version: 0.1.1 (62)

English is not my native language, I'm sorry for any inconvience

**Comment by BenSova** [comment]
Your English is perfect, don't worry!

What shows up if you run `fdesetup status` in terminal?

**Comment by michkozak** [comment]
Hey, fellow Pole here ;). There is no bug. Patched Sur is telling you that FileVault is enabled because... it's enabled, as evident from your screenshot. It clearly says it's enabled and that the recovery key has been set ("Funkcja FileVault jest włączona dla dysku Macintosh HD" and "Klucz odzyskiwania został ustawiony") and gives you an option to turn it off ("Wyłącz FileVault...").

It's not just about locking the padlock in the lower left corner of the preference pane. You need to turn off FileVault entirely.

**Comment by BenSova** [comment]
Oh! You know, I just really translate screenshots sometimes. I also saw that extra bit of text and didn't twice about it. Thanks for checking! So, @skfar you need to fully disable FileVault, not just locking the padlock, like he said.

**Comment by skfar** [comment]
Thanks, I will do it during upcoming weekend and share the result

**Comment by skfar** [comment]
I've fully disabled FileVault and then... everything went smoothly. 

@michkozak was right (dzięki)

Thanks for help :)
