### ISSUE TITLE
Macos High Sierra Support

### ISSUE THREAD

**Issue by Grandboy46** [BenSova/Patched-Sur#456]
Hello

I have a 2010 iMac and I want to replace it's gpu with a metal compatible one and then update to big sur but it is inconvenient to update to catalina first. Can you please support older macos versions?

Thx

**Comment by BenSova** [comment]
In short, no.

That would require rewriting the patcher completely. I originally started this as something to do when I was bored, so I didn't plan on supporting any OS under Catalina mostly because I didn't expect it to become big, especially since I thought dosdude1 would steal the show. He didn't, and this became a huge project. I **will** support all the way back to OS X Mavericks with my next patcher.  

So, once again, no.
