### ISSUE TITLE
Error 1x1

### ISSUE THREAD

**Issue by VanillaRainb0w** [BenSova/Patched-Sur#90]
Hello!

Just upgraded my Macbook Pro 9.2 from Catalina to Big Sur via Patched Sur 0.0.4 and everything is fine. Just tried running the Patch Kexts app but everytime I get an error:

Error 1x1
Message: "Password"
"csr-active-config appears to be set incorrectly:
csr-active-config %e7%03%00%00

To fix this, please boot the setvars EFI utility, the boot back into macOS..."

I have no idea to what I need to do.

Thanx in advance.

**Comment by VanillaRainb0w** [comment]
Solved tuning again the setup via USB, opened terminal and ran install-setvars.sh first, then patch-kexts.sh giving the right mac os volume ( "/Volumes/MacOsBigSur" in my case).

**Comment by GOCOROAR** [comment]
Did you do the solution after installing big sur? Because I have the same problem!

**Comment by VanillaRainb0w** [comment]
Just read above your comment 🤦

**Comment by GOCOROAR** [comment]
Thanks, can you tell me how you put it so that it goes to the correct volume.

**Comment by VanillaRainb0w** [comment]
They are already there when you create the usb via Patched Sur 0.0.4

Just reboot from USB, open terminal and follow the instructions of my previous comment.

**Comment by BenSova** [comment]
You could also boot into the EFI Boot, but v0.1.0 will include some proofing for this so you won't have to, it'll just tell you to restart and try again.

**Comment by andresfgomezf** [comment]
Hi! I just tried to install the setvars.sh directly from the termina and usb, the only thing is that I did not find the setvars.sh file on the usb, help

**Comment by BenSova** [comment]
You don't need `setvars.sh`. `install-setvars.sh` which makes the EFI Boot partition on the USB *that booting into solves this problem* is run by Patched Sur when you create the usb in the pre-install app. If you have a Late 2013 iMac you don't need to patch the kexts, so that's why the EFI Boot doesn't solve the problem on those Macs.

**Comment by andresfgomezf** [comment]
Hey, thanks for tour answer! I got the exact same error Error 1x1
Message: "Password"
"csr-active-config appears to be set incorrectly:
csr-active-config %e7%03%00%00

To fix this, please boot the setvars EFI utility, the boot back into macOS..."

I got a MacBook Pro mid 2012 I5, the problem comes when I run the patched sur to resolve de wifi, but when I run it I always receive the same error and I haven't been able to resolve it yet

**Comment by andresfgomezf** [comment]
Hey! Me here again, disregard! lol! I was able to resolve it, I just had to disable the csrutil again and disable the authenticated root and everything worked, it now seems to be working okay and now I got wifi! Thanks anyways for taking the time to answer and keep it up, here another Colombian Mac user just happy to be able to give it one more use to the laptop! Have a good one!

**Comment by BenSova** [comment]
Closing in favor of #27

**Comment by RoySkytt** [comment]
If you’re experiencing this issue just boot your Mac up by pressing the “alt” key and boot up from your Big Sur USB drive and open the terminal and put type in
“csrutil disable” and afterwards 
“csrutil authenticated-root disable
reboot”

**Comment by BenSova** [comment]
Or you could do what everyone forgets to do:

# Boot into the EFI Boot on the installer USB.

**Comment by andresfgomezf** [comment]
Yes, I got it resolved, however I went back to Catalina anyways, feel like it wasn't as smooth as before!

**Comment by durchblicker1** [comment]
Hi,

I have the same problem: I made an update from Big Sur 11.1 to 11.2.3 with Patch Sur 0.12 beta. 
 I made the update directly from the patcher without making an USB Stick. Now I get the same Error as mentioned. I have no WiFi an no USB works. 
How to solve this issuse without BigSure-USB Stick, and without working Wifi? 

thanks

**Comment by BenSova** [comment]
> I made the update directly from the patcher without making an USB Stick.

Reboot into recovery mode (CMD-R when you are turning on your mac, it doesn't matter what version of recovery) and run `nvram csr-active-config=%7f%08%00%00` in terminal.

**Comment by kimJiyeongha** [comment]
Hello I have the same problem with the kexts, I tried using your code above “nvram csr-active-config=%7f%08%00%00” but it returns “nvram: Error setting variable - ‘csr-active-config’: (iokit/common) not permitted”

could you please help me out on what I can do? I updated from 11.1 to 11.2.3 using the post-install app, the installation went fine but I just cant patch the kext due to Error 1x1/Password Error.

**Comment by BenSova** [comment]
Do CMD-OPTION-SHIFT-R for recovery mode then.

**Comment by kimJiyeongha** [comment]
Hi I really appreciate the quick reply. Sorry for bothering you again, but this time it says “nvram: Error setting variable - ‘csr-active-config’: (iokit/common) general error” instead.

**Comment by BenSova** [comment]
Maybe you typed something wrong? Can you send a picture of the command you put into it?

**Comment by kimJiyeongha** [comment]
![image](https://user-images.githubusercontent.com/82958372/115639353-f053e400-a346-11eb-9c64-26e0d2904c0f.jpg)

Thanks again for the quick reply! Here’s a photo of the code and what it returns in the terminal.

**Comment by sluttyracoon** [comment]
Hi I am getting the same issue as kimJiyeongha, csrutil disable does not work, above command is not permitted, csrutil clear works but when restart to use csrutil i get the same error,what is the work around for this? i am stuck with no wifi

**Comment by naco-siren** [comment]
Same issue here (Mac Mini 2012).
EFI Boot doesn't help, while booting into installer thru USB won't allow me:![image](https://user-images.githubusercontent.com/8222638/131235828-1d230f17-76f6-4761-80b5-443ffdd5861b.jpeg)
