### ISSUE TITLE
Version 0.0.4 Beta not compatible with Catalina

### ISSUE THREAD

**Issue by schmutzige-dame** [BenSova/Patched-Sur#91]
How should you be able to create a USB boot stick with version 0.0.4.Beta under Catalina let alone Mojave (0.0.3.Beta) if Beta 0.0.4 is not compatible with Catalina and Beta 0.0.3 for Mojave. For example, no rope can be created under Catalina with Beta 0.0.4. You get the message that you should use macOS 11. But what if it is not running on the computer and you have to patch it? Somehow I don't put the prenzip.

Another problem is when several drives are connected to the mac, Beta 0.0.4 is to display the USB when creating a USB stick. You have to separately deactivate the drives in the hard disk service program that you do not need. Only then can Beta 0.0.4 display the USB drive (Sick).

___________________________________________________________________________

Wie solll man mit der Verion 0.0.4.Beta unter Catalina geschweige denn Mojave (0.0.3.Beta) einen USB-Bootstick erstellen können wenn Beta 0.0.4 nicht für Catalina und Beta 0.0.3 für Mojave kompatiebel sind. So zum beispiel lässt sich kein Strick unter Catalina mit Beta 0.0.4 erstellen. Man bekommt den Hinweis, dass man macOS 11 benutzen soll. Aber wie, wenn es nicht auf dem Rechner läuft und man den patchen muss? Irgenwie versehe ich das Prenzip nicht.

Ein weiteres Problem ist, wenn mehrere Laufwerke am mac angeschlossen sind, ist die Beta 0.0.4 beim Erstellen eines USB-STicks den USB anzuzeigen. Man muss vorher gesondert die Laufwerke im Festplatten Diensprogramm deaktivieren die man nicht benötigt. Erst dann kann Beta 0.0.4 das USB-Laufwerk (Sick) anzeigen.

**Comment by BenSova** [comment]
I will not support Mojave. Done deal there, it's easier for me, and it's discouragement for Macs that don't have Metal. Also, there's two apps. One to build the usb and get to Big Sur, and another you can use for the rest of your Mac's life. Post-Install-**Extra** you will not need pretty much ever, as **Patched-Sur.dmg** is what you always should be downloading. Obviously when you are a developer, you want to use newer APIs you'll have more access to the things you need, and you'll have more features at your hands. That's why the post install app is solely for Big Sur and up **because you don't need it in Catalina**. If you are not downloading Patched-Sur.dmg, you can close this issue, because a lot of other people would have DMed me about this, and others on GitHub that are stuck on Catalina have already tested it.

Also, yes I know about the drive list problem, that's part of the other issues.
